services:
  db:
    image: postgres:13
    container_name: meu_postgres_local
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strw4xmk
      POSTGRES_DB: meupet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: